com/t/marfeel-com-privacy-policy/10383",
    "Wildcard match": 0
  },
  {
    "ID": "e29ce395-f286-4105-a447-f7aaed278d29",
    "Platform": "Marfeel",
    "Category": "Analytics",
    "Cookie / Data Key name": "compass_uid",
    "Domain": "events.newsroom.bi",
    "Description": "This cookie is used to store Marfeel user id",
    "Retention period": "180 days",
    "Data Controller": "Marfeel",
    "User Privacy & GDPR Rights Portals": "https://community.marfeel.com/t/marfeel-com-privacy-policy/10383",
    "Wildcard match": 0
  },
  {
    "ID": "6fc1ee3e-14dc-4578-86ea-8655d1e6d1e7",
    "Platform": "Marfeel",
    "Category": "Analytics",
    "Cookie / Data Key name": "___m_rec",
    "Domain": "events.newsroom.bi",
    "Description": "This cookie is used to store data about recirculation module",
    "Retention period": "180 days",
    "Data Controller": "Marfeel",
    "User Privacy & GDPR Rights Portals": "https://community.marfeel.com/t/marfeel-com-privacy-policy/10383",
    "Wildcard match": 0
  },
  {
    "ID": "a8584f16-c5e5-4240-b64e-5340ce4b61fc",
    "Platform": "Groovinads",
    "Category": "Marketing",
    "Cookie / Data Key name": "GRV_BHV_UID",
    "Domain": ".groovinads.com",
    "Description": "This cookie is used to store the user's unique identifier",
    "Retention period": "45 days",
    "Data Controller": "Groovinads",
    "User Privacy & GDPR Rights Portals": "https://shopping.groovinads.com/privacy",
    "Wildcard match": 1
  },
  {
    "ID": "5b35c4a0-2a8f-4113-9fbb-c7f1033d71f4",
    "Platform": "Groovinads",
    "Category": "Marketing",
    "Cookie / Data Key name": "GRV_BHV_IDCC",
    "Domain": ".groovinads.com",
    "Description": "This cookie is used to store the user's geographical location",
    "Retention period": "45 days",
    "Data Controller": "Groovinads",
    "User Privacy & GDPR Rights Portals": "https://shopping.groovinads.com/privacy",
    "Wildcard match": 1
  },
  {
    "ID": "ec79561e-ef16-4785-b578-9ce51251568e",
    "Platform": "Groovinads",
    "Category": "Marketing",
    "Cookie / Data Key name": "GRV_BHV_SKU",
    "Domain": ".groovinads.com",
    "Description": "This cookie is used to store SKU of user",
    "Retention period": "45 days",
    "Data Controller": "Groovinads",
    "User Privacy & GDPR Rights Portals": "https://shopping.groovinads.com/privacy",
    "Wildcard match": 1
  },
  {
    "ID": "b477fac4-5a91-43c5-86fa-1032ad14ad6f",
    "Platform": "Groovinads",
    "Category": "Marketing",
    "Cookie / Data Key name": "GRV_BHV_IDCAT",
    "Domain": ".groovinads.com",
    "Description": "This cookie is used to uniqiue identifier.",
    "Retention period": "45 days",
    "Data Controller": "Groovinads",
    "User Privacy & GDPR Rights Portals": "https://shopping.groovinads.com/privacy",
    "Wildcard match": 1
  },
  {
    "ID": "335a2537-2cb3-4f13-82b0-4ad850eaecab",
    "Platform": "Groovinads",
    "Category": "Marketing",
    "Cookie / Data Key name": "GRV_BHV_DATE",
    "Domain": ".groovinads.com",
    "Description": "This cookie is used to store Date for user perfernces.",
    "Retention period": "45 days",
    "Data Controller": "Groovinads",
    "User Privacy & GDPR Rights Portals": "https://shopping.groovinads.com/privacy",
    "Wildcard match": 1
  },
  {
    "ID": "1e27dd9f-9df7-490a-9f12-16433dd6d64b",
    "Platform": "Groovinads",
    "Category": "Marketing",
    "Cookie / Data Key name": "GRV_IDU",
    "Domain": ".groovinads.com",
    "Description": "This cookie is used to store the user's unique identifier",
    "Retention period": "296 days",
    "Data Controller": "Groovinads",
    "User Privacy & GDPR Rights Portals": "https://shopping.groovinads.com/privacy",
    "Wildcard match": 0
  },
  {
    "ID": "29a01ce5-dc07-43d9-9b91-40d5c158a06d",
    "Platform": "Groovinads",
    "Category": "Marketing",
    "Cookie / Data Key name": "NPA",
    "Domain": ".groovinads.com",
    "Description": "This cookie is used to store the user's browsing history",
    "Retention period": "45 days",
    "Data Controller": "Groovinads",
    "User Privacy & GDPR Rights Portals": "https://shopping.groovinads.com/privacy",
    "Wildcard match": 1
  },
  {
    "ID": "11873da5-d2ea-4a17-9939-7182e7a9c1e4",
    "Platform": "Groovinads",
    "Category": "Marketing",
    "Cookie / Data Key name": "GRV_BHV_BRND_",
    "Domain": ".groovinads.com",
    "Description": "This cookie is used to brand of user's perfernces",
    "Retention period": "45 days",
    "Data Controller": "Groovinads",
    "User Privacy & GDPR Rights Portals": "https://shopping.groovinads.com/privacy",
    "Wildcard match": 1
  },
  {
    "ID": "d4a1b275-463e-4342-81ea-fe319395e1ff",
    "Platform": "Groovinads",
    "Category": "Marketing",
    "Cookie / Data Key name": "GRV_google",
    "Domain": ".groovinads.com",
    "Description": "This cookie is used to store user's google search history",
    "Retention period": "45 days",
    "Data Controller": "Groovinads",
    "User Privacy & GDPR Rights Portals": "https://shopping.groovinads.com/privacy",
    "Wildcard match": 0
  },
  {
    "ID": "cc42aa30-1ff9-4b99-bddf-d0e71151a965",
    "Platform": "Bidence",
    "Category": "Marketing",
    "Cookie / Data Key name": "duid_update_time",
    "Domain": ".bidence.net",
    "Description": "Registers a unique ID that identifies the user's device during return visits. Used for conversion tracking and to measure the efficacy of online ads.",
    "Retention period": "2 years",
    "Data Controller": "Bidence",
    "User Privacy & GDPR Rights Portals": "https://bidence.com/page/pp.html",
    "Wildcard match": 0
  },
  {
    "ID": "2daeb207-112b-43fc-9e64-c965d6a947d2",
    "Platform": "Bidence",
    "Category": "Marketing",
    "Cookie / Data Key name": "_ssp_update_time",
    "Domain": ".bidence.net",
    "Description": "This cookie is used to store unique identifiers timestamp",
    "Retention period": "2 years",
    "Data Controller": "Bidence",
    "User Privacy & GDPR Rights Portals": "https://bidence.com/page/pp.html",
    "Wildcard match": 1
  },
  {
    "ID": "4528d5ba-74e1-4716-a55f-1507fde154f0",
    "Platform": "Bidence",
    "Category": "Marketing",
    "Cookie / Data Key name": "_dsp_uid",
    "Domain": ".bidence.net",
    "Description": "This cookie is used to store unique identifiers",
    "Retention period": "2 years",
    "Data Controller": "Bidence",
    "User Privacy & GDPR Rights Portals": "https://bidence.com/page/pp.html",
    "Wildcard match": 1
  },
  {
    "ID": "add48aa4-1893-4302-8d91-cddcdf87e5a6",
    "Platform": "Zendesk",
    "Category": "Functional",
    "Cookie / Data Key name": "connect.sid",
    "Domain": ".zendesk.com",
    "Description": "This is used for user sessions and is strictly necessary for the Community. Session cookies allow websites to remember users within a website when they move between web pages. These cookies tell the server what pages to show the user so the user doesn’t have to remember where they left off or start navigating the site all over again.",
    "Retention period": "Session",
    "Data Controller": "Zendesk",
    "User Privacy & GDPR Rights Portals": "https://www.zendesk.com/company/agreements-and-terms/privacy-notice/",
    "Wildcard match": 0
  },
  {
    "ID": "9060ce7d-4498-4c94-8cf1-8a8e8f0909df",
    "Platform": "Zendesk",
    "Category": "Functional",
    "Cookie / Data Key name": "_zendesk_cookie",
    "Domain": "",
    "Description": "This cookie saves arbitrary preference settings. Two factor authentication features and device tracking will not work without it.",
    "Retention period": "1 year",
    "Data Controller": "Zendesk",
    "User Privacy & GDPR Rights Portals": "https://www.zendesk.com/company/agreements-and-terms/privacy-notice/",
    "Wildcard match": 0
  },
  {
    "ID": "b5f966e9-a86f-4196-94c4-3887413a39b0",
    "Platform": "Zendesk",
    "Category": "Functional",
    "Cookie / Data Key name": "zte2095",
    "Domain": ".zendesk.com",
    "Description": "This cookie is used to identify the domain/subdomain the Chat Widget is located on.",
    "Retention period": "Session",
    "Data Controller": "Zendesk",
    "User Privacy & GDPR Rights Portals": "https://www.zendesk.com/company/agreements-and-terms/privacy-notice/",
    "Wildcard match": 0
  },
  {
    "ID": "daeacb39-08b2-41d2-adc9-a787f24352a2",
    "Platform": "Zendesk",
    "Category": "Functional",
    "Cookie / Data Key name": "__zlcprivacy",
    "Domain": ".zendesk.com",
    "Description": "This cookie store visitor's decision on CookieLaw",
    "Retention period": "1 year",
    "Data Controller": "Zendesk",
    "User Privacy & GDPR Rights Portals": "https://www.zendesk.com/company/agreements-and-terms/privacy-notice/",
    "Wildcard match": 0
  },
  {
    "ID": "5a498a0a-26c7-485d-bd60-e0e54923a3ee",
    "Platform": "Zendesk",
    "Category": "Functional",
    "Cookie / Data Key name": "__zlcmid",
    "Domain": ".zendesk.com",
    "Description": "This cookie Chat Widget offers out-of-the-box cookie consent management, see here: Enabling cookie consent for the Chat widget & Web Widget. Alternatively, these Chat Cookies respect external cookie bot functionality as well.",
    "Retention period": "1 year",
    "Data Controller": "Zendesk",
    "User Privacy & GDPR Rights Portals": "https://www.zendesk.com/company/agreements-and-terms/privacy-notice/",
    "Wildcard match": 0
  },
  {
    "ID": "6bf1c399-58e5-4eb4-8d08-0bc824ef2ac8",
    "Platform": "Zendesk",
    "Category": "Functional",
    "Cookie / Data Key name": "_answer_bot_service_session",
    "Domain": ".zendesk.com",
    "Description": "This cookie stores unique session key for Answer Bot product. Used to uniquely identify a user session when using Answer Bot Article Recommendations.",
    "Retention period": "Session",
    "Data Controller": "Zendesk",
    "User Privacy & GDPR Rights Portals": "https://www.zendesk.com/company/agreements-and-terms/privacy-notice/",
    "Wildcard match": 0
  },
  {
    "ID": "193c8c38-2844-4578-8f1f-830f503478d6",
    "Platform": "Zendesk",
    "Category": "Functional",
    "Cookie / Data Key name": "ZD-zE_oauth",
    "Domain": ".zendesk.com",
    "Description": "This cookie stores the authentication token once the user has been authenticated.Web Widget (Classic) offers pre-built API functionality for cookie consent; see here: Web Widget (Classic) Cookie Permission in Developer Center. Alternatively, these Cookies respect external cookie bot functionality as well.",
    "Retention period": "2 hours",
    "Data Controller": "Zendesk",
    "User Privacy & GDPR Rights Portals": "https://www.zendesk.com/company/agreements-and-terms/privacy-notice/",
    "Wildcard match": 0
  },
  {
    "ID": "e680a392-193f-4638-acff-ef5629544051",
    "Platform": "Zendesk",
    "Category": "Functional",
    "Cookie / Data Key name": "_zendesk_session",
    "Domain": "",
    "Description": "This cookie stores account ID, route for internal service calls and the cross-site request forgery token.",
    "Retention period": "8 hours",
    "Data Controller": "Zendesk",
    "User Privacy & GDPR Rights Portals": "https://www.zendesk.com/company/agreements-and-terms/privacy-notice/",
    "Wildcard match": 0
  },
  {
    "ID": "230fdca6-66b5-